### ISSUE TITLE
cramp.in is down

### ISSUE THREAD

**Issue by frankpinto** [lifo/cramp#71]
Trying to check out the site @ http://cramp.in/ but it throws an Application Error, take a look.

**Comment by brunoocasali** [comment]
:+1:

**Comment by teacplusplus** [comment]
+

**Comment by omenkzz** [comment]
and still down

**Comment by lucasallan** [comment]
I'm getting in touch with @lifo so we can fix it asap.

**Comment by lucasallan** [comment]
Hey guys, I'm closing this issue since we're already talking about it on https://github.com/lifo/cramp/issues/68
